### ISSUE TITLE
关于训练的问题

### ISSUE THREAD

**Issue by ygmuy** [zwx8981/BIQA_project#11]
作者你好，请问一下我想用自己的数据集进行训练，也必须在正式训练时生成对应的失真图像才可以进行么

**Comment by xiongxiongtiao** [comment]
你好，训练好的scnn权重已经放在github上，可以直接用，如果想加入新的失真类型就需要自己再生成重新训练。在自己的数据集上训练可以不用生成，直接用训练好的scnn权重就好发自我的iPhone------------------ 原始邮件 ------------------发件人: ygmuy  ***@***.***>发送时间: 2021年8月29日 09:34收件人: zwx8981/DBCNN ***@***.***>抄送: Subscribed ***@***.***>主题: 回复：[zwx8981/DBCNN] 关于训练的问题 (#11)
作者你好，请问一下我想用自己的数据集进行训练，也必须在正式训练时生成对应的失真图像才可以进行么

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/zwx8981/DBCNN/issues/11",
"url": "https://github.com/zwx8981/DBCNN/issues/11",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by w615933060** [comment]
您好，数据集中不包含失真类型，只有图像和mos值，可以直接训练吗

**Comment by zwx8981** [comment]
你好，可以直接训练的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: w615933060 ***@***.***&gt;
发送时间: 2021年8月29日 11:12
收件人: zwx8981/DBCNN ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[zwx8981/DBCNN] 关于训练的问题 (#11)





 
您好，数据集中不包含失真类型，只有图像和mos值，可以直接训练吗
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
